<?php $helper = $this->helper('Bss\LazyImageLoader\Helper\Data'); ?>
<?php if ($helper->isEnabled()): ?>
	<style>
		img.lazy {
			background: url(<?php echo $helper->getLazyImage(); ?>) no-repeat;
		    background-size: <?php echo $this->helper('Bss\LazyImageLoader\Helper\Data')->getLoadingWidth(); ?>px;
		    background-position: center;
		}
	</style>

	<script type="text/javascript">
		require(['jquery','bss/unveil'],function($){
			$(document).ready(function() {
				$("img.lazy").unveil(<?php echo $this->helper('Bss\LazyImageLoader\Helper\Data')->getThreshold() ?>, function(){
					var self = $(this);
					setTimeout(function(){
						self.removeClass('lazy');
					}, 0);
				});
			});

		});
	</script>

<?php endif; ?>
